language: node_js
cache: yarn
node_js:
  - '10'

jobs:
  include:
    - stage: 'Run tests'
      script:
        - yarn test
        - yarn lint
    - stage: 'Publish to NPM'
      script:
        - yarn build
        - yarn semantic-release
